# Generated by Django 4.2.25 on 2025-11-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_variation_delete_variations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("marca", "marca")], max_length=100
            ),
        ),
    ]
