# Generated by Django 4.2.25 on 2025-12-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="mail",
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
