# Generated by Django 4.2.25 on 2025-10-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category_name", models.CharField(max_length=50, unique=True)),
                ("Description", models.CharField(blank=True, max_length=255)),
                ("slug", models.CharField(max_length=100, unique=True)),
                (
                    "cat_image",
                    models.ImageField(blank=True, upload_to="photos/categories"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
